version: '3.8'

services:
  web-about:
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - "8001:8001"
  web-research:
    build:
      context: .
      dockerfile: Dockerfile2

  web-ct519:
    build:
      context: .
      dockerfile: Dockerfile3
    ports:
      - "8003:8003"
  web-landing-1:
    build:
      context: .
      dockerfile: Dockerfile4
    ports:
      - "8000:8000"
  web-landing-2:
    build:
      context: .
      dockerfile: Dockerfile5
    ports:
      - "7999:7999"
  web-landing-3:
    build:
      context: .
      dockerfile: Dockerfile6
    ports:
      - "7998:7998"


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    depends_on:
      - web-about
      - web-research
      - web-ct519
      - web-landing-1
      - web-landing-2
      - web-landing-3
